### PR TITLE
Solving an undeclared variable access. Small whitespace cleanup.

### PR DESCRIPTION
**Pull request by EdwardThorsten**

### CODE REVIEW

**Comment by EdwardThorsten** [comment]
Apologies for the bad patch. It should be ok now.

**Comment by sofar** [comment]
No, this is incorrect.

Instead, all that needs to be done is:

```
droplift = {}
```

at the top, and then all is well.

**Comment by EdwardThorsten** [comment]
... looks like I still need to read more about Lua. Thank you.

**Comment by sofar** [comment]
This is more like it, I think this can be squashed on merge.

**Pull request merged**
